/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <string>
#include <cmath>
#include "console.h"

using namespace std;

namespace A{
int x = 1;
int y = 2;
}

namespace B{
double x = 1.1;
double y = 2.1;
}


int main() {
    //method 1 using all definition from the namespace
//    using namespace A;
//    using namespace B;
//    cout << "x value in A is "<< x << ", y value in A is "<< y << endl;

    //method 2 directly access the variables in different namespace
//    cout << "x value in A is "<< A::x << ", y value in A is "<< A::y << endl;
//    cout << "x value in B is "<< B::x << ", y value in B is "<< B::y << endl;

    //method 3 using some certain variables in namespace while the variables are access frequently
    using A::x, B::y;
    cout << "x value in A is " << x << endl;
    cout << "y value in B is " << y << endl;
    return 0;
}
