/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <string>
#include <cmath>
#include "console.h"

using namespace std;
const double pi = acos(-1);

class circle{
    //This is a class constructed for description of the circle.
private:
    int radius;
public:
    void setCircle();

    double getPerimeter();

    double getArea();

};

void circle::setCircle(){
    cout << "Please enter the value of radius:" << endl;
    cin >> radius;
}

double circle::getPerimeter(){
    return pi *  radius;
}

double circle::getArea(){
    return pi * radius * radius;
}


int main() {
    circle circle1;
    double area;
    double perimeter;
    circle1.setCircle();
    area = circle1.getArea();
    perimeter = circle1.getPerimeter();
    cout << "The area is " << area <<endl;
    cout << "The perimeter is " << perimeter << endl;
    return 0;
}
