/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <string>
#include "console.h"
#include "testing/SimpleTest.h"
#include <fstream>

using namespace std;

int main() {
    string line;
    cout << "string default value: " << line << endl;
    //console io

    ifstream fin("res/input.txt");
    ofstream fout("res/output.txt");

    getline(fin, line);
    fout << line << endl;

    return 0;
}
