/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <string>
#include "console.h"
#include "map.h"
#include "simpio.h"

using namespace std;

int main() {
    Map<string, int> word_freq;

    while(true){
        string word = getLine("Enter your word");
        if(word == "")
            break;
        word_freq[word] += 1;
    }
    cout << word_freq << endl;


    return 0;
}
