/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <string>
#include <cmath>
#include "console.h"

using namespace std;

int main() {
    int i = 36;
    int *p = &i;
    cout << "the value of i is " << i << endl;
    cout << "the loc of i is" << &i << endl;
    cout << "the value pointer pointed is "<< *p << endl;
    cout << "the pointer loc is " << p << endl;

    return 0;
}
